[telegram]
token = "6130457410:AAG8jDlWwyFQv1-u8XYnpDhtXaliPo3YrEY"
workers = 1
admins = [6262157003]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 29616312
api_hash = "dd1a05ab4c47a5a037cc067cf4bded27"

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = "https://t.me/prime_hritu"
issues = "https://t.me/prime_hritu"
channel = "https://t.me/private_bots"
